/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using com.Messente.Omnichannel.Client;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing DeliveryReportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DeliveryReportApiTests
    {
        private DeliveryReportApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DeliveryReportApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeliveryReportApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DeliveryReportApi
            //Assert.IsInstanceOfType(typeof(DeliveryReportApi), instance, "instance is a DeliveryReportApi");
        }

        
        /// <summary>
        /// Test RetrieveDeliveryReport
        /// </summary>
        [Test]
        public void RetrieveDeliveryReportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? omnimessageId = null;
            //var response = instance.RetrieveDeliveryReport(omnimessageId);
            //Assert.IsInstanceOf<DeliveryReportResponse> (response, "response is DeliveryReportResponse");
        }
        
    }

}
