/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using com.Messente.Omnichannel.Client;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing OmnimessageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OmnimessageApiTests
    {
        private OmnimessageApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OmnimessageApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OmnimessageApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OmnimessageApi
            //Assert.IsInstanceOfType(typeof(OmnimessageApi), instance, "instance is a OmnimessageApi");
        }

        
        /// <summary>
        /// Test CancelScheduledMessage
        /// </summary>
        [Test]
        public void CancelScheduledMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? omnimessageId = null;
            //instance.CancelScheduledMessage(omnimessageId);
            
        }
        
        /// <summary>
        /// Test SendOmnimessage
        /// </summary>
        [Test]
        public void SendOmnimessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Omnimessage omnimessage = null;
            //var response = instance.SendOmnimessage(omnimessage);
            //Assert.IsInstanceOf<OmniMessageCreateSuccessResponse> (response, "response is OmniMessageCreateSuccessResponse");
        }
        
    }

}
