/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = com.Messente.Omnichannel.Client.OpenAPIDateConverter;

namespace com.Messente.Omnichannel.Model
{
    /// <summary>
    /// Defines the delivery channel
    /// </summary>
    /// <value>Defines the delivery channel</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Channel
    {
        /// <summary>
        /// Enum Sms for value: sms
        /// </summary>
        [EnumMember(Value = "sms")]
        Sms = 1,

        /// <summary>
        /// Enum Viber for value: viber
        /// </summary>
        [EnumMember(Value = "viber")]
        Viber = 2,

        /// <summary>
        /// Enum Whatsapp for value: whatsapp
        /// </summary>
        [EnumMember(Value = "whatsapp")]
        Whatsapp = 3

    }

}
