/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = com.Messente.Omnichannel.Client.OpenAPIDateConverter;

namespace com.Messente.Omnichannel.Model
{
    /// <summary>
    /// Textual value which corresponds to ResponseErrorCode
    /// </summary>
    /// <value>Textual value which corresponds to ResponseErrorCode</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ResponseErrorTitle
    {
        /// <summary>
        /// Enum Notfound for value: Not found
        /// </summary>
        [EnumMember(Value = "Not found")]
        Notfound = 1,

        /// <summary>
        /// Enum Forbidden for value: Forbidden
        /// </summary>
        [EnumMember(Value = "Forbidden")]
        Forbidden = 2,

        /// <summary>
        /// Enum Unauthorized for value: Unauthorized
        /// </summary>
        [EnumMember(Value = "Unauthorized")]
        Unauthorized = 3,

        /// <summary>
        /// Enum Invaliddata for value: Invalid data
        /// </summary>
        [EnumMember(Value = "Invalid data")]
        Invaliddata = 4,

        /// <summary>
        /// Enum InternalServerError for value: Internal Server Error
        /// </summary>
        [EnumMember(Value = "Internal Server Error")]
        InternalServerError = 5,

        /// <summary>
        /// Enum Missingdata for value: Missing data
        /// </summary>
        [EnumMember(Value = "Missing data")]
        Missingdata = 6

    }

}
