/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing ErrorItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorItemTests
    {
        // TODO uncomment below to declare an instance variable for ErrorItem
        //private ErrorItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorItem
            //instance = new ErrorItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorItem
        /// </summary>
        [Test]
        public void ErrorItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorItem
            //Assert.IsInstanceOfType<ErrorItem> (instance, "variable 'instance' is a ErrorItem");
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Test]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
