/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing Message
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageTests
    {
        // TODO uncomment below to declare an instance variable for Message
        //private Message instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Message
            //instance = new Message();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Message
        /// </summary>
        [Test]
        public void MessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Message
            //Assert.IsInstanceOfType<Message> (instance, "variable 'instance' is a Message");
        }

        /// <summary>
        /// Test deserialize a Viber from type Message
        /// </summary>
        [Test]
        public void ViberDeserializeFromMessageTest()
        {
            // TODO uncomment below to test deserialize a Viber from type Message
            //Assert.IsInstanceOf<Message>(JsonConvert.DeserializeObject<Message>(new Viber().ToJson()));
        }
        /// <summary>
        /// Test deserialize a SMS from type Message
        /// </summary>
        [Test]
        public void SMSDeserializeFromMessageTest()
        {
            // TODO uncomment below to test deserialize a SMS from type Message
            //Assert.IsInstanceOf<Message>(JsonConvert.DeserializeObject<Message>(new SMS().ToJson()));
        }
        /// <summary>
        /// Test deserialize a WhatsApp from type Message
        /// </summary>
        [Test]
        public void WhatsAppDeserializeFromMessageTest()
        {
            // TODO uncomment below to test deserialize a WhatsApp from type Message
            //Assert.IsInstanceOf<Message>(JsonConvert.DeserializeObject<Message>(new WhatsApp().ToJson()));
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Test]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'Validity'
        /// </summary>
        [Test]
        public void ValidityTest()
        {
            // TODO unit test for the property 'Validity'
        }

    }

}
