/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing MessageResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageResultTests
    {
        // TODO uncomment below to declare an instance variable for MessageResult
        //private MessageResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageResult
            //instance = new MessageResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageResult
        /// </summary>
        [Test]
        public void MessageResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageResult
            //Assert.IsInstanceOfType<MessageResult> (instance, "variable 'instance' is a MessageResult");
        }


        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Test]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Test]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

    }

}
