/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing Omnimessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OmnimessageTests
    {
        // TODO uncomment below to declare an instance variable for Omnimessage
        //private Omnimessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Omnimessage
            //instance = new Omnimessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Omnimessage
        /// </summary>
        [Test]
        public void OmnimessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Omnimessage
            //Assert.IsInstanceOfType<Omnimessage> (instance, "variable 'instance' is a Omnimessage");
        }


        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'DlrUrl'
        /// </summary>
        [Test]
        public void DlrUrlTest()
        {
            // TODO unit test for the property 'DlrUrl'
        }
        /// <summary>
        /// Test the property 'TimeToSend'
        /// </summary>
        [Test]
        public void TimeToSendTest()
        {
            // TODO unit test for the property 'TimeToSend'
        }

    }

}
