/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing SMS
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SMSTests
    {
        // TODO uncomment below to declare an instance variable for SMS
        //private SMS instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SMS
            //instance = new SMS();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SMS
        /// </summary>
        [Test]
        public void SMSInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SMS
            //Assert.IsInstanceOfType<SMS> (instance, "variable 'instance' is a SMS");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Autoconvert'
        /// </summary>
        [Test]
        public void AutoconvertTest()
        {
            // TODO unit test for the property 'Autoconvert'
        }
        /// <summary>
        /// Test the property 'Udh'
        /// </summary>
        [Test]
        public void UdhTest()
        {
            // TODO unit test for the property 'Udh'
        }

    }

}
