/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing WhatsApp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WhatsAppTests
    {
        // TODO uncomment below to declare an instance variable for WhatsApp
        //private WhatsApp instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WhatsApp
            //instance = new WhatsApp();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhatsApp
        /// </summary>
        [Test]
        public void WhatsAppInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WhatsApp
            //Assert.IsInstanceOfType<WhatsApp> (instance, "variable 'instance' is a WhatsApp");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Test]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'Audio'
        /// </summary>
        [Test]
        public void AudioTest()
        {
            // TODO unit test for the property 'Audio'
        }

    }

}
