/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing WhatsAppText
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WhatsAppTextTests
    {
        // TODO uncomment below to declare an instance variable for WhatsAppText
        //private WhatsAppText instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WhatsAppText
            //instance = new WhatsAppText();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhatsAppText
        /// </summary>
        [Test]
        public void WhatsAppTextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WhatsAppText
            //Assert.IsInstanceOfType<WhatsAppText> (instance, "variable 'instance' is a WhatsAppText");
        }


        /// <summary>
        /// Test the property 'PreviewUrl'
        /// </summary>
        [Test]
        public void PreviewUrlTest()
        {
            // TODO unit test for the property 'PreviewUrl'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
