/* 
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.Messente.Omnichannel.Api;
using com.Messente.Omnichannel.Model;
using com.Messente.Omnichannel.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.Messente.Omnichannel.Test
{
    /// <summary>
    ///  Class for testing WhatsAppDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WhatsAppDocumentTests
    {
        // TODO uncomment below to declare an instance variable for WhatsAppDocument
        //private WhatsAppDocument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WhatsAppDocument
            //instance = new WhatsAppDocument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhatsAppDocument
        /// </summary>
        [Test]
        public void WhatsAppDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WhatsAppDocument
            //Assert.IsInstanceOfType<WhatsAppDocument> (instance, "variable 'instance' is a WhatsAppDocument");
        }


        /// <summary>
        /// Test the property 'Caption'
        /// </summary>
        [Test]
        public void CaptionTest()
        {
            // TODO unit test for the property 'Caption'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
